---
default: &DEFAULT
  - cơm ngoài
  - cơm chiên
  - mỳ xào bò
  - beefsteak
  - mỳ gói nước thịt bò

Monday:
  - *DEFAULT
  - bún bò

Tuesday:
  - *DEFAULT
  - bún riêu

Wednesday:
  - *DEFAULT
  - hủ tiếu
  - bánh canh

Thursday:
  - *DEFAULT
  - bún mọc

Friday:
  - *DEFAULT
  - miến gà
  - bún gà  